on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Coverage report
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Steup Node
        uses: actions/setup-node@v4.1.0

      - name: Install Deps
        run: npm install

      - name: Link
        run: npm link geo
        
      - name: Test
        run: npm run test

      - name: Generate report
        run: npm run cover
        
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: report.xml
          badge: true
          format: markdown
          output: both
